### ISSUE TITLE
Couldn't customize the style of the button

### ISSUE THREAD

**Issue by BruceW-Lelouch** [mike-roberts/ngx-plaid-link#14]
I couldn't customize the button style.

I use to change it in '/ngx-plaid-link/fesm2015/ngx-plaid-link.js' and  '/ngx-plaid-link/fesm5/ngx-plaid-link.js', which use to work.

Do you have any idea how I could change it?
Thank you！

**Comment by mike-roberts** [comment]
The built it button has always had an `ngStyle` property that you can pass an object to https://angular.io/api/common/NgStyle . As a general best practice you shouldn't mess with stuff in node_modules folder, it will get wiped out if you reinstall or update the package. It also won't persist if you have a deploy where npm/yarn install runs wherever you're deploying it, ie Netlify or similar.
