### ISSUE TITLE
Having issue with the import service ngx-plaid-link.service and  ngx-plaid-link-handler

### ISSUE THREAD

**Issue by deeppatidar** [mike-roberts/ngx-plaid-link#2]
I am facing issues in import the interfaces, services and handler into the component, i need that service and functionality into the different module, first I imported NgxPlaidLinkModule into app-module but no luck so I tried it by importing it into my specific module where I am using it but still getting error Cannot find module './interfaces, /ngx-plaid-link-handler, ./ngx-plaid-link.service.

Please help how can I resolve this.

**Comment by ghost** [comment]
write ngx-plaid-link/lib/interfaces, ngx-plaid-link/lib/ngx-plaid-link-handler and ngx-plaid-link/lib/ngx-plaid-link.service instead

**Comment by mike-roberts** [comment]
Ah sorry, README has code copied from my local dev setup. I'll fix that shortly.

**Comment by mike-roberts** [comment]
you should just be able to import everything from `ngx-plaid-link` like `import { PlaidConfig, NgxPlaidLinkService, PlaidLinkHandler } from 'ngx-plaid-link';` but you could also import from lib like mathais said as well.
