### ISSUE TITLE
receivedRedirectUri not available in 1.0.3 package

### ISSUE THREAD

**Issue by Guillaumejfrt** [mike-roberts/ngx-plaid-link#25]
Hi @mike-roberts ,

Are your changes from december available on the `1.0.3` package version? 

I can see on your repo that the `PlaidConfig` interface contains the `receivedRedirectUri` parameter, however I don't have it when installing node_modules in my app on the `1.0.3` version.

Here is my `PlaidConfig` interface:

```
export interface PlaidConfig {
    apiVersion?: string;
    clientName?: string;
    env: string;
    key?: string;
    onLoad?: Function;
    onSuccess: Function;
    onExit: Function;
    onEvent?: Function;
    product: Array<string>;
    selectAccount?: boolean;
    token?: string;
    webhook?: string;
    countryCodes?: string[];
}

```

So , I can't use correcly the `receivedRedirectUri` parameter.

Do I miss something or is a problem a package update?

Best regards
Guillaume

**Comment by andrew-lewell** [comment]
I am also interested to know this. receivedRedirectUri is an essential parameter for mobile OAuth flows, which is the norm in Europe. 

Thanks

**Comment by JonnyVR1** [comment]
Hi both, I created a PR with the fix for this but the author hasn't responded or merged the code, nor has he updated the npm repository with the initial recievedRedirectUri change.  As I needed it for myself I have made it available through npm https://www.npmjs.com/package/ngx-plaid-link2

**Comment by werdnasiwel** [comment]
@JonnyVR1 - does your variation work with the Plaid OAuth flows?

**Comment by JonnyVR1** [comment]
> @JonnyVR1 - does your variation work with the Plaid OAuth flows?

Yes

**Comment by mike-roberts** [comment]
1.0.4 is now published, which has this property in it.
