### ISSUE TITLE
Not getting error in method onEvent if something goes wrong while adding bank

### ISSUE THREAD

**Issue by finsightcpa** [mike-roberts/ngx-plaid-link#26]
I am trying to save error for error in banks but not getting in any of the method of following:
`this.plaidLinkService
			.createPlaid(
				Object.assign({}, this.config, {
					onSuccess: (token, metadata) =>
						this.onSuccess(token, metadata),
					onExit: (error, metadata) => this.onExit(error, metadata),
					onEvent: (eventName, metadata) =>
						this.onEvent(eventName, metadata),
				})
			)
			.then((handler: PlaidLinkHandler) => {
				this.plaidLinkHandler = handler;
                this.open();
                console.log(23423);
			});`
I thought it will come in onEvent, but failing. Or is there any other method in which error can be caught please let me know.

**Comment by mike-roberts** [comment]
Error should come in through the `onExit` event, although according to Plaid docs it should also come through `onEvent` as well. Not really sure what's going on, I'm getting error events through onEvent in our implementation.
