### ISSUE TITLE
None of the examples work for me?

### ISSUE THREAD

**Issue by ErraticFox** [mike-roberts/ngx-plaid-link#27]
Hello, I've went through all three examples on a fresh Angular 11 project and nothing seems to work and I'm not even getting any errors. I do have NgxPlaidLinkModule imported in my imports in my `app.moduel.ts`

Using the ngxPlaidLink directives: I get the error `Can't bind to 'countryCodes' since it isn't a known property of 'button'.`, when I remove that directive, set my API key, and set up all the functions with a log of their events, nothing happens when I click the button. 

Using the provided button `mr-ngx-plaid-link-button` I just get that it's not a know element.

as for the third example, it just simply does nothing again when I press the button.

**Comment by mike-roberts** [comment]
Do you still need help with this? It seems like you didn't import the module correctly or where you were trying to use it. Going to close since it's been almost a year and is not likely a problem with this package.
