### ISSUE TITLE
Error using library with link_token in production.plaid.com

### ISSUE THREAD

**Issue by andrew-lewell** [mike-roberts/ngx-plaid-link#29]
Hi, I am having an issue using ngx-plaid-link with a link_token instead of the old public_key, specifically in production.plaid.com.

Using the link_token flow works fine in sandbox and development mode, but when in production mode I am getting this error:

"Error authenticating public key. This public key is not enabled for product "assets" in all the countries provided: "GB". Please contact Support (https://dashboard.plaid.com/support/new) to be enabled."

However, when I use the old flow with a public_key instead of getting a link_token, Link opens and connects with Plaid.

Is this a known issue? I can provide code snippets if needed.

**Comment by andrew-lewell** [comment]
The solution to this is to also pass countryCode to initialize Link, as well as whilst getting your link_token. This issue is known by Plaid and they are looking into it.

**Comment by SerzhanHelena** [comment]
@andrew-lewell can you please share how do you migrate on link token?
