### ISSUE TITLE
Version Issues for using GET keyword (An accessor cannot be declared in an ambient context) ERROR

### ISSUE THREAD

**Issue by rushi053** [mike-roberts/ngx-plaid-link#35]
Getting this error while building the project as the Typescript version of project is below 3.6 and it wont allow GET Keyword.

ERROR in ../node_modules/ngx-plaid-link/lib/ngx-plaid-link-button.component.d.ts
An accessor cannot be declared in an ambient context.

 get nativeWindow(): ICustomWindow;
 
 Is there an older version available to bypass this or any other solutions without upgrading the angular/typescript version?

**Comment by mike-roberts** [comment]
No answer really except upgrade your Angular/Typescript. https://angular.io/guide/releases#support-policy-and-schedule Anything below 11 is no longer supported or receiving any security updates or anything so you really should update.
