### ISSUE TITLE
Account_Subtype Filtering

### ISSUE THREAD

**Issue by kgmorales** [mike-roberts/ngx-plaid-link#37]
In the Plaid Docs, it says you're able to customize the select accounts menu from the modal.

https://plaid.com/docs/api/tokens/#link-token-create-request-account-filters

Are you allowed to do this within the ngx-plaid-link directive?

**Comment by mike-roberts** [comment]
Those docs are for the backend request to get a link token, so you'll need to do that in your API when you make the request to Plaid to get a link token.
