### ISSUE TITLE
Country Codes missing from ngx-plaid-link

### ISSUE THREAD

**Issue by ghost** [mike-roberts/ngx-plaid-link#4]
Plaid now supports country codes (for example 'US', 'CA' or 'GB'). However, they don't seem to work in ngx-plaid-ling yet. It would be great if someone could update it. Thanks!

**Comment by mike-roberts** [comment]
Hi, are there docs for this?

**Comment by ghost** [comment]
It is featured in the official Plaid Documentation: https://plaid.com/docs/#integrating-with-link 
It should just be a matter of adding the Parameter ‘countryCodes: string[]’ in the config object. I would do it myself but I have just started using Angular and don’t know where exactly I would have to change it. The work you’ve done already is a great help, by the way!

**Comment by mike-roberts** [comment]
Ah, thanks. I'll get a new release out this week with that fix :)

**Comment by ghost** [comment]
Thanks a lot!

**Comment by mike-roberts** [comment]
@mathiasriedel alright, that was an easy change. Releasead 1.0.2 to npm with countrycode support.

**Comment by ghost** [comment]
This is really helpful!
