### ISSUE TITLE
Version 13.0.1 is not compiling

### ISSUE THREAD

**Issue by chbohm** [mike-roberts/ngx-plaid-link#48]
I run ng build  (ng version 11.0.7) having as dependency ngx-plaid-link 13.0.1 and I am getting compiling issues like
Error: node_modules/ngx-plaid-link/lib/ngx-plaid-link.service.d.ts:18:21 - error TS2694: Namespace '"C:/projects/etana/crm/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

18     static ɵfac: i0.ɵɵFactoryDeclaration<NgxPlaidLinkService, never>;

Using 1.0.4 everything looks fine

**Comment by trentprynn** [comment]
This is not a bug, to use ngx-plaid-link@13 you should be using angular@13 (ngx-plaid-link@13 is built using angular ivy compilation)

take a look at the angular compatibility chart 
https://github.com/mike-roberts/ngx-plaid-link#angular-compatibility-chart
