### ISSUE TITLE
Product attribute doesn't work when sending the request.

### ISSUE THREAD

**Issue by BruceW-Lelouch** [mike-roberts/ngx-plaid-link#5]
Hi, 
This product is great and it really helps a lot. But I came across some issues about how to use it, so I want to ask for help.
I used the provided button and with an optional attribute 'product'. I set it as ['transaction'], but I found it send the request with the default setting ['auth'].  
`            <mr-ngx-plaid-link-button>
              '''
              [product]="['transactions']"
              '''
          </mr-ngx-plaid-link-button>`
Do I need to change the code in ngx-plaid-link.js? Change the 'this.product = this.defaultProps.product;' to 'plaidLinkLoader.product'?
`var NgxPlaidLinkButtonComponent = /** @class */ (function () {
    function NgxPlaidLinkButtonComponent(plaidLinkLoader) {
        this.plaidLinkLoader = plaidLinkLoader;
        this.defaultProps = {
            '''
            product: ['auth'],
            className: 'plaid-link-button'
        };
        '''
        this.product = this.defaultProps.product;
        '''
    }`
Or any other options?
I change the 'product' because Amex isn't supported by Plaid Auth. When the product is 'transaction', Amex will be shown the panel for selecting the banks, while with 'auth', it won't.
Hope you can share your ideas with me.
Thank you.

**Comment by DovakhinMRK** [comment]
@BruceW-Lelouch  I tried it with:
[product]="'transactions'" 
and it works.
