### ISSUE TITLE
compatibility with API after  November 2022?

### ISSUE THREAD

**Issue by coanpape** [mike-roberts/ngx-plaid-link#50]
I support a company using this for its website as well as an iOS and a soon to be released Android version.  I have seen notes for both the Android and iOS versions of Plaid Link that the back end API will no longer support versions (or Plaid Link) from before Oct 2021...  
e.g.  [https://github.com/plaid/plaid-link-ios/blob/master/README.md]

are you aware of the changes and whether or not they impact this project?

Thank you

**Comment by mike-roberts** [comment]
I don't see anything about that in the [web docs](https://plaid.com/docs/link/web/) but it's listed right on the front page in their [iOS](https://plaid.com/docs/link/ios/) and [Android](https://plaid.com/docs/link/android/) docs, so I assume there is nothing to be done here.

With the iOS/Android SDK they can't just implement breaking changes that change how their SDK works with their backend but with the web version they're serving up the JS fresh every time, so as long as the public API doesn't change they can do whatever they want with their JS file.
