### ISSUE TITLE
Plaid workflow get stuck after returning to the app from the Plaid oAuth workflow

### ISSUE THREAD

**Issue by NedimBusiness** [mike-roberts/ngx-plaid-link#52]
Plaid workflow was working for a few months in my application, but suddenly few weeks before it stopped working even though I did not make any changes in the code. I am using ngx-plaid-link library for my Ionic app. I updated Angular to version 13 and ngx-plaid-link as well, but that did not fix the issue.

When I return from the website where Plaid redirects me to authenticate with the bank account, I get to the screen which says that I need to return to the bank account window to continue linking the account, even though I finished linking and it returned me back to my app with the oauth_state_id.

![Screenshot_90](https://user-images.githubusercontent.com/102909707/161430540-36beeaf2-a6e9-4b0a-ab6e-3d8c49d57bde.png)
![Screenshot_91](https://user-images.githubusercontent.com/102909707/161430550-75e169e0-c896-4f43-8268-80c68892cca5.png)

**Comment by NedimBusiness** [comment]
Also, I got this reply from Plaid's support team:
Plaid Support Apr 5, 2022

Hi Nedim,
 
Thanks for the follow up!
 
I am not sure how the library you are using fetches the Web SDK. If it downloads it (hard codes it) instead of fetching it dynamically as such:
 
<script src="[https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>](https://cdn.plaid.com/link/v2/stable/link-initialize.js%22%3E%3C/script%3E)
 
then it is possible that our Web SDK changes have caused the library to break. We recommend everyone to fetch the Javascript (Web) SDK dynamically, so changes are automatically accounted for. 
 
I also suggest you follow our [oAuth guide](https://plaid.com/docs/link/oauth/#desktop-web-mobile-web-or-react) for React (which I assume will be similar) to see if you are missing any of the steps.
 
I hope this helps, Nedim!
 
Best,
Souhayl
Plaid Support

**Comment by mike-roberts** [comment]
It's fetched via that URL as you can see here https://github.com/mike-roberts/ngx-plaid-link/blob/master/src/lib/ngx-plaid-link.service.ts#L32 so not really sure what the issue is. Looks like you're doing this in a mobile app, maybe Cordova or Capacitor? In which case you should really use the Plaid native SDKs because they don't really support webviews anymore, you can see that they suggest it on their docs at https://plaid.com/docs/link/webview/ 

> Plaid does not recommend the use of webviews for new integrations. Plaid's SDKs for [Android](https://plaid.com/docs/link/android/), [iOS](https://plaid.com/docs/link/ios/), and [React Native](https://plaid.com/docs/link/react-native/) provide the easiest and best way to build a mobile Plaid experience and are recommended for all developers.
