### ISSUE TITLE
"Don't see your bank? Search instead"

### ISSUE THREAD

**Issue by andrew-lewell** [mike-roberts/ngx-plaid-link#54]
This link does not seem to be working, nothing happens when you click it: 

![image](https://user-images.githubusercontent.com/32621888/165343439-5ecabeed-9ac7-4fcf-a744-03e9fbafb193.png)

Angular 13 and ngx-plaid-link 13.0.1

**Comment by mike-roberts** [comment]
Odds are that's an issue with the Plaid JS itself. The only thing ngx-plaid-link does is create a script element with the source of the plaid link JS from their docs and trigger that JS. Once that launches, everything in the Plaid window is controlled via their JS that loads and launches that iFrame that we have no control over.

I'll test it out and see if I can see if it's anything on our side, but most likely it's an issue with Plaid.

**Comment by mike-roberts** [comment]
Yeah, so confirmed this. That link just focuses on the search field, and that's internal to the plaid link js. Looks like this screen doesn't have a search field and that link probably shouldn't even be there but that's an issue with Plaid and not this library.
