### ISSUE TITLE
updating-items-via-link is not working : when we pass token

### ISSUE THREAD

**Issue by HarishkrVerma** [mike-roberts/ngx-plaid-link#8]
when we link with plaid it's working fine issue in updating(sending token ) plaid  API's give's 200 ok response but my onSuccess method is not calling   

```
     this.plaidConfig = {
                clientName: 'test',
                env: this.plaidData.plaid_config.environment,
                key: this.plaidData.plaid_config.public_key,
                onSuccess: this.onSuccess,
                onExit: this.onExit,
                onEvent: null,
                product: ['transactions'],
                token: this.plaidData.refress_token, // send box -token 
            };
        }
```

```
from(this.plaidLinkService.createPlaid(Object.assign(this.plaidConfig, {
            onSuccess: (public_token, metadata) => this.onSuccess(public_token, metadata),
            onExit: (error, metadata) => this.onExit(error, metadata),
        }))).subscribe(handler => {
            this.plaidLinkHandler = handler;
            this.plaidLinkHandler.open();
            this.isFirst = false;
        });
```

The onSuccess function is not working according to doc(https://plaid.com/docs/#updating-items-via-link) it should be worked but it's not working 

Thanks in advance

**Comment by kunalht** [comment]
Any updates on this? Not working for me either

**Comment by HarishkrVerma** [comment]
Hi @kunalht  for this problem I have a temporary solution for this problem 
in onExit function check error otherwise consider as success 
 `onExit: (error, metadata) => this.onExit(error, metadata),`

like 
```
this.onExit(error, metadata){
  if(!error){
    //success     
   }else{
     //error 
   }
}
```

**Comment by kunalht** [comment]
thanks , although this won't update the account right? It wouldn't show the Plaid link like it should, right?

**Comment by kunalht** [comment]
It works! I was passing the same used public token every time and not creating a new one. Update accounts works perfectly.

**Comment by mike-roberts** [comment]
> It works! I was passing the same used public token every time and not creating a new one. Update accounts works perfectly.

Does that mean this issue is no longer a problem? Can I close this or is there something that needs to be done here?
